<?php
/**
 * SdkOrder
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  RPay\POK\PaymentsSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * RPay API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RPay\POK\PaymentsSdk\Model;

use \ArrayAccess;
use \RPay\POK\PaymentsSdk\ObjectSerializer;

/**
 * SdkOrder Class Doc Comment
 *
 * @category Class
 * @package  RPay\POK\PaymentsSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class MerchantOrder implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MerchantOrder';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'amount' => 'float',
        'capturedAmount' => 'float',
        'currencyCode' => 'string',
        'products' => '\RPay\POK\PaymentsSdk\Model\SdkOrderProduct[]',
        'shippingCost' => 'float',
        'finalAmount' => 'float',
        'createdAt' => '\DateTime',
        'expiresAt' => '\DateTime',
        'redirectUrl' => 'string',
        'failRedirectUrl' => 'string',
        'merchantCustomReference' => 'string',
        'merchant' => '\RPay\POK\PaymentsSdk\Model\Merchant',
        '_self' => 'array',
        'paymentMethod' => 'string',
        'transaction_id' => 'string',
        'transaction' => '\RPay\POK\PaymentsSdk\Model\TransactionOrder',
        'capturedSplitWithAmount' => 'float',
        'originalCurrencyCode' => 'string',
        'originalAmount' => 'float',
        'appliedExchangeRate' => 'float',
        'description' => 'string',
        'isCompleted' => 'bool',
        'isRefunded' => 'bool',
        'user' => 'array',
        'sdkOrderPaymentFlows' => 'array',
        'issuer' => 'string',
        'selectedBranchId' => 'string',
        'hasFailedPaymentFlow' => 'bool',
        'isConfirmed' => 'bool',
        'isCaptured' => 'bool',
        'isCanceled' => 'bool',
        'canBeCaptured' => 'bool',
        'deeplink' => 'string',
        'webhookUrl' => 'string',
        'autoCapture' => 'bool',
        'splitWithAmount' => 'float',
        'isMarketplace' => 'bool',
        'isRefundable' => 'bool',
        'isDisputed' => 'bool',
        'refundableAmount' => 'float',

    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'amount' => null,
        'capturedAmount' => null,
        'currencyCode' => null,
        'products' => null,
        'shippingCost' => null,
        'finalAmount' => null,
        'createdAt' => 'date',
        'expiresAt' => 'date',
        'redirectUrl' => null,
        'failRedirectUrl' => null,
        'merchantCustomReference' => null,
        'merchant' => null,
        '_self' => null,
        'paymentMethod' => null,
        'transaction_id' => null,
        'transaction' => null,
        'capturedSplitWithAmount' => null,
        'originalCurrencyCode' => null,
        'originalAmount' => null,
        'appliedExchangeRate' => null,
        'description' => null,
        'isCompleted' => null,
        'isRefunded' => null,
        'user' => null,
        'sdkOrderPaymentFlows' => null,
        'issuer' => null,
        'selectedBranchId' => null,
        'hasFailedPaymentFlow' => null,
        'isConfirmed' => null,
        'isCaptured' => null,
        'isCanceled' => null,
        'canBeCaptured' => null,
        'deeplink' => null,
        'webhookUrl' => null,
        'autoCapture' => null,
        'splitWithAmount' => null,
        'isMarketplace' => null,
        'isRefundable' => null,
        'isDisputed' => null,
        'refundableAmount' => null,
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'amount' => 'amount',
        'capturedAmount' => 'capturedAmount',
        'currencyCode' => 'currencyCode',
        'products' => 'products',
        'shippingCost' => 'shippingCost',
        'finalAmount' => 'finalAmount',
        'createdAt' => 'createdAt',
        'expiresAt' => 'expiresAt',
        'redirectUrl' => 'redirectUrl',
        'failRedirectUrl' => 'failRedirectUrl',
        'merchantCustomReference' => 'merchantCustomReference',
        'merchant' => 'merchant',
        '_self' => '_self',
        'paymentMethod' => 'paymentMethod',
        'transaction_id' => 'transactionId',
        'transaction' => 'transaction',
        'capturedSplitWithAmount' => 'capturedSplitWithAmount',
        'originalCurrencyCode' => 'originalCurrencyCode',
        'originalAmount' => 'originalAmount',
        'appliedExchangeRate' => 'appliedExchangeRate',
        'description' => 'description',
        'isCompleted' => 'isCompleted',
        'isRefunded' => 'isRefunded',
        'user' => 'user',
        'sdkOrderPaymentFlows' => 'sdkOrderPaymentFlows',
        'issuer' => 'issuer',
        'selectedBranchId' => 'selectedBranchId',
        'hasFailedPaymentFlow' => 'hasFailedPaymentFlow',
        'isConfirmed' => 'isConfirmed',
        'isCaptured' => 'isCaptured',
        'isCanceled' => 'isCanceled',
        'canBeCaptured' => 'canBeCaptured',
        'deeplink' => 'deeplink',
        'webhookUrl' => 'webhookUrl',
        'autoCapture' => 'autoCapture',
        'splitWithAmount' => 'splitWithAmount',
        'isMarketplace' => 'isMarketplace',
        'isRefundable' => 'isRefundable',
        'isDisputed' => 'isDisputed',
        'refundableAmount' => 'refundableAmount',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'amount' => 'setAmount',
        'capturedAmount' => 'setCapturedAmount',
        'currencyCode' => 'setCurrencyCode',
        'products' => 'setProducts',
        'shippingCost' => 'setShippingCost',
        'finalAmount' => 'setFinalAmount',
        'createdAt' => 'setCreatedAt',
        'expiresAt' => 'setExpiresAt',
        'redirectUrl' => 'setRedirectUrl',
        'failRedirectUrl' => 'setFailRedirectUrl',
        'merchantCustomReference' => 'setMerchantCustomReference',
        'merchant' => 'setMerchant',
        '_self' => 'setSelf',
        'transaction_id' => 'setTransactionId',
        'transaction' => 'setTransaction',
        'paymentMethod' => 'setPaymentMethod',
        'capturedSplitWithAmount' => 'setCapturedSplitWithAmount',
        'originalCurrencyCode' => 'setOriginalCurrencyCode',
        'originalAmount' => 'setOriginalAmount',
        'appliedExchangeRate' => 'setAppliedExchangeRate',
        'description' => 'setDescription',
        'isCompleted' => 'setIsCompleted',
        'isRefunded' => 'setIsRefunded',
        'user' => 'setUser',
        'sdkOrderPaymentFlows' => 'setSdkOrderPaymentFlows',
        'issuer' => 'setIssuer',
        'selectedBranchId' => 'setSelectedBranchId',
        'hasFailedPaymentFlow' => 'setHasFailedPaymentFlow',
        'isConfirmed' => 'setIsConfirmed',
        'isCaptured' => 'setIsCaptured',
        'isCanceled' => 'setIsCanceled',
        'canBeCaptured' => 'setCanBeCaptured',
        'deeplink' => 'setDeeplink',
        'webhookUrl' => 'setWebhookUrl',
        'autoCapture' => 'setAutoCapture',
        'splitWithAmount' => 'setSplitWithAmount',
        'isMarketplace' => 'setIsMarketplace',
        'isRefundable' => 'setIsRefundable',
        'isDisputed' => 'setIsDisputed',
        'refundableAmount' => 'setRefundableAmount',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'amount' => 'getAmount',
        'capturedAmount' => 'getCapturedAmount',
        'currencyCode' => 'getCurrencyCode',
        'products' => 'getProducts',
        'shippingCost' => 'getShippingCost',
        'finalAmount' => 'getFinalAmount',
        'createdAt' => 'getCreatedAt',
        'expiresAt' => 'getExpiresAt',
        'redirectUrl' => 'getRedirectUrl',
        'failRedirectUrl' => 'getFailRedirectUrl',
        'merchantCustomReference' => 'getMerchantCustomReference',
        'merchant' => 'getMerchant',
        '_self' => 'getSelf',
        'paymentMethod' => 'getPaymentMethod',
        'transaction_id' => 'getTransactionId',
        'transaction' => 'getTransaction',
        'capturedSplitWithAmount' => 'getCapturedSplitWithAmount',
        'originalCurrencyCode' => 'getOriginalCurrencyCode',
        'originalAmount' => 'getOriginalAmount',
        'appliedExchangeRate' => 'getAppliedExchangeRate',
        'description' => 'getDescription',
        'isCompleted' => 'getIsCompleted',
        'isRefunded' => 'getIsRefunded',
        'user' => 'getUser',
        'sdkOrderPaymentFlows' => 'getSdkOrderPaymentFlows',
        'issuer' => 'getIssuer',
        'selectedBranchId' => 'getSelectedBranchId',
        'hasFailedPaymentFlow' => 'getHasFailedPaymentFlow',
        'isConfirmed' => 'getIsConfirmed',
        'isCaptured' => 'getIsCaptured',
        'isCanceled' => 'getIsCanceled',
        'canBeCaptured' => 'getCanBeCaptured',
        'deeplink' => 'getDeeplink',
        'webhookUrl' => 'getWebhookUrl',
        'autoCapture' => 'getAutoCapture',
        'splitWithAmount' => 'getSplitWithAmount',
        'isMarketplace' => 'getIsMarketplace',
        'isRefundable' => 'getIsRefundable',
        'isDisputed' => 'getIsDisputed',
        'refundableAmount' => 'getRefundableAmount',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): array
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['amount'] = $data['amount'] ?? null;
        $this->container['capturedAmount'] = $data['capturedAmount'] ?? null;
        $this->container['currencyCode'] = $data['currencyCode'] ?? 'ALL';
        $this->container['products'] = $data['products'] ?? null;
        $this->container['shippingCost'] = $data['shippingCost'] ?? null;
        $this->container['finalAmount'] = $data['finalAmount'] ?? null;
        $this->container['createdAt'] = $data['createdAt'] ?? null;
        $this->container['expiresAt'] = $data['expiresAt'] ?? null;
        $this->container['redirectUrl'] = $data['redirectUrl'] ?? null;
        $this->container['failRedirectUrl'] = $data['failRedirectUrl'] ?? null;
        $this->container['merchantCustomReference'] = $data['merchantCustomReference'] ?? null;
        $this->container['merchant'] = $data['merchant'] ?? null;
        $this->container['_self'] = $data['_self'] ?? null;
        $this->container['transaction_id'] = $data['transaction_id'] ?? null;
        $this->container['transaction'] = $data['transaction'] ?? null;
        $this->container['paymentMethod'] = $data['paymentMethod'] ?? null;
        $this->container['capturedSplitWithAmount'] = $data['capturedSplitWithAmount'] ?? null;
        $this->container['originalCurrencyCode'] = $data['originalCurrencyCode'] ?? null;
        $this->container['originalAmount'] = $data['originalAmount'] ?? null;
        $this->container['appliedExchangeRate'] = $data['appliedExchangeRate'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['isCompleted'] = $data['isCompleted'] ?? null;
        $this->container['isRefunded'] = $data['isRefunded'] ?? null;
        $this->container['user'] = $data['user'] ?? null;
        $this->container['sdkOrderPaymentFlows'] = $data['sdkOrderPaymentFlows'] ?? null;
        $this->container['issuer'] = $data['issuer'] ?? null;
        $this->container['selectedBranchId'] = $data['selectedBranchId'] ?? null;
        $this->container['hasFailedPaymentFlow'] = $data['hasFailedPaymentFlow'] ?? null;
        $this->container['isConfirmed'] = $data['isConfirmed'] ?? null;
        $this->container['isCaptured'] = $data['isCaptured'] ?? null;
        $this->container['isCanceled'] = $data['isCanceled'] ?? null;
        $this->container['canBeCaptured'] = $data['canBeCaptured'] ?? null;
        $this->container['deeplink'] = $data['deeplink'] ?? null;
        $this->container['webhookUrl'] = $data['webhookUrl'] ?? null;
        $this->container['autoCapture'] = $data['autoCapture'] ?? null;
        $this->container['splitWithAmount'] = $data['splitWithAmount'] ?? null;
        $this->container['isMarketplace'] = $data['isMarketplace'] ?? null;
        $this->container['isRefundable'] = $data['isRefundable'] ?? null;
        $this->container['isDisputed'] = $data['isDisputed'] ?? null;
        $this->container['refundableAmount'] = $data['refundableAmount'] ?? null;

    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['capturedAmount'] === null) {
            $invalidProperties[] = "'capturedAmount' can't be null";
        }
        if ($this->container['currencyCode'] === null) {
            $invalidProperties[] = "'currencyCode' can't be null";
        }
        if (!is_null($this->container['shippingCost']) && ($this->container['shippingCost'] < 0)) {
            $invalidProperties[] = "invalid value for 'shippingCost', must be bigger than or equal to 0.";
        }
        if ($this->container['finalAmount'] === null) {
            $invalidProperties[] = "'finalAmount' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['expiresAt'] === null) {
            $invalidProperties[] = "'expiresAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id): self
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float
     */
    public function getAmount(): float
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float $amount amount
     *
     * @return self
     */
    public function setAmount($amount): self
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets capturedAmount
     *
     * @return float
     */
    public function getCapturedAmount(): float
    {
        return $this->container['capturedAmount'];
    }

    /**
     * Sets capturedAmount
     *
     * @param float $capturedAmount capturedAmount
     *
     * @return self
     */
    public function setCapturedAmount($capturedAmount): self
    {
        $this->container['capturedAmount'] = $capturedAmount;

        return $this;
    }


    /**
     * Gets currencyCode
     *
     * @return string
     */
    public function getCurrencyCode(): string
    {
        return $this->container['currencyCode'];
    }

    /**
     * Sets currencyCode
     *
     * @param string $currencyCode currencyCode
     *
     * @return self
     */
    public function setCurrencyCode($currencyCode): self
    {
        $this->container['currencyCode'] = $currencyCode;

        return $this;
    }

    /**
     * Gets products
     *
     * @return SdkOrderProduct[]|null
     */
    public function getProducts(): ?array
    {
        return $this->container['products'];
    }

    /**
     * Sets products
     *
     * @param SdkOrderProduct[]|null $products products
     *
     * @return self
     */
    public function setProducts($products): self
    {
        $this->container['products'] = $products;

        return $this;
    }

    /**
     * Gets shippingCost
     *
     * @return float|null
     */
    public function getShippingCost(): ?float
    {
        return $this->container['shippingCost'];
    }

    /**
     * Sets shippingCost
     *
     * @param float|null $shippingCost shippingCost
     *
     * @return self
     */
    public function setShippingCost($shippingCost): self
    {

        if (!is_null($shippingCost) && ($shippingCost < 0)) {
            throw new \InvalidArgumentException('invalid value for $shippingCost when calling MerchantOrder., must be bigger than or equal to 0.');
        }

        $this->container['shippingCost'] = $shippingCost;

        return $this;
    }

    /**
     * Gets finalAmount
     *
     * @return float
     */
    public function getFinalAmount(): float
    {
        return $this->container['finalAmount'];
    }

    /**
     * Sets finalAmount
     *
     * @param float $finalAmount finalAmount
     *
     * @return self
     */
    public function setFinalAmount($finalAmount): self
    {
        $this->container['finalAmount'] = $finalAmount;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt): self
    {
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets expiresAt
     *
     * @return \DateTime
     */
    public function getExpiresAt(): \DateTime
    {
        return $this->container['expiresAt'];
    }

    /**
     * Sets expiresAt
     *
     * @param \DateTime $expiresAt expiresAt
     *
     * @return self
     */
    public function setExpiresAt($expiresAt): self
    {
        $this->container['expiresAt'] = $expiresAt;

        return $this;
    }

    /**
     * Gets redirectUrl
     *
     * @return string|null
     */
    public function getRedirectUrl()
    {
        return $this->container['redirectUrl'];
    }

    /**
     * Gets paymentMethod
     *
     * @return string|null
     */
    public function getPaymentMethod(): string
    {
        return $this->container['paymentMethod'];
    }

    /**
     * Sets redirectUrl
     *
     * @param string|null $redirectUrl redirectUrl
     *
     * @return self
     */
    public function setRedirectUrl($redirectUrl)
    {
        $this->container['redirectUrl'] = $redirectUrl;

        return $this;
    }

    /**
     * Sets paymentMethod
     *
     * @param string|null $paymentMethod
     *
     * @return self
     */
    public function setPaymentMethod(?string $paymentMethod): self
    {
        $this->container['paymentMethod'] = $paymentMethod;

        return $this;
    }

    /**
     * Gets failRedirectUrl
     *
     * @return string|null
     */
    public function getFailRedirectUrl()
    {
        return $this->container['failRedirectUrl'];
    }

    /**
     * Sets failRedirectUrl
     *
     * @param string|null $failRedirectUrl failRedirectUrl
     *
     * @return self
     */
    public function setFailRedirectUrl($failRedirectUrl)
    {
        $this->container['failRedirectUrl'] = $failRedirectUrl;

        return $this;
    }

    /**
     * Gets merchantCustomReference
     *
     * @return string|null
     */
    public function getMerchantCustomReference()
    {
        return $this->container['merchantCustomReference'];
    }

    /**
     * Sets merchantCustomReference
     *
     * @param string|null $merchantCustomReference merchantCustomReference
     *
     * @return self
     */
    public function setMerchantCustomReference($merchantCustomReference)
    {
        $this->container['merchantCustomReference'] = $merchantCustomReference;

        return $this;
    }

    /**
     * Gets merchant
     *
     * @return \RPay\POK\PaymentsSdk\Model\Merchant|null
     */
    public function getMerchant()
    {
        return $this->container['merchant'];
    }

    /**
     * Sets merchant
     *
     * @param \RPay\POK\PaymentsSdk\Model\Merchant|null $merchant merchant
     *
     * @return self
     */
    public function setMerchant($merchant)
    {
        $this->container['merchant'] = $merchant;

        return $this;
    }

    public function getTransactionId(): string
    {
        return $this->container['transaction_id'];
    }

    public function setTransactionId(?string $transactionId): self
    {
        $this->container['transaction_id'] = $transactionId;

        return $this;
    }

    public function getTransaction(): ?TransactionOrder
    {
        return $this->container['transaction'];
    }

    public function setTransaction(?TransactionOrder $transaction): self
    {
        $this->container['transaction'] = $transaction;

        return $this;
    }

    /**
     * Gets self
     *
     * @return ?array
     */
    public function getSelf(): ?array
    {
        return $this->container['_self'];
    }

    /**
     * Sets self
     *
     *
     * @param ?array $self
     * @return self
     */
    public function setSelf(?array $self): self
    {
        $this->container['_self'] = $self;

        return $this;
    }

    public function getCapturedSplitWithAmount()
    {
        return $this->container['capturedSplitWithAmount'];
    }

    public function setCapturedSplitWithAmount($capturedSplitWithAmount): self
    {
        $this->container['capturedSplitWithAmount'] = $capturedSplitWithAmount;
        return $this;
    }

    public function getOriginalCurrencyCode()
    {
        return $this->container['originalCurrencyCode'];
    }

    public function setOriginalCurrencyCode($originalCurrencyCode): self
    {
        $this->container['originalCurrencyCode'] = $originalCurrencyCode;
        return $this;
    }

    public function getOriginalAmount()
    {
        return $this->container['originalAmount'];
    }

    public function setOriginalAmount($originalAmount): self
    {
        $this->container['originalAmount'] = $originalAmount;
        return $this;
    }

    public function getAppliedExchangeRate()
    {
        return $this->container['appliedExchangeRate'];
    }

    public function setAppliedExchangeRate($appliedExchangeRate): self
    {
        $this->container['appliedExchangeRate'] = $appliedExchangeRate;
        return $this;
    }

    public function getDescription()
    {
        return $this->container['description'];
    }

    public function setDescription($description): self
    {
        $this->container['description'] = $description;
        return $this;
    }

    public function getIsCompleted()
    {
        return $this->container['isCompleted'];
    }

    public function setIsCompleted($isCompleted): self
    {
        $this->container['isCompleted'] = $isCompleted;
        return $this;
    }

    public function getIsRefunded()
    {
        return $this->container['isRefunded'];
    }

    public function setIsRefunded($isRefunded): self
    {
        $this->container['isRefunded'] = $isRefunded;
        return $this;
    }

    public function getUser()
    {
        return $this->container['user'];
    }

    public function setUser($user): self
    {
        $this->container['user'] = $user;
        return $this;
    }

    public function getSdkOrderPaymentFlows()
    {
        return $this->container['sdkOrderPaymentFlows'];
    }

    public function setSdkOrderPaymentFlows($sdkOrderPaymentFlows): self
    {
        $this->container['sdkOrderPaymentFlows'] = json_decode(json_encode($sdkOrderPaymentFlows), true);
        return $this;
    }

    public function getIssuer()
    {
        return $this->container['issuer'];
    }

    public function setIssuer($issuer): self
    {
        $this->container['issuer'] = $issuer;
        return $this;
    }

    public function getSelectedBranchId()
    {
        return $this->container['selectedBranchId'];
    }

    public function setSelectedBranchId($selectedBranchId): self
    {
        $this->container['selectedBranchId'] = $selectedBranchId;
        return $this;
    }

    public function getHasFailedPaymentFlow()
    {
        return $this->container['hasFailedPaymentFlow'];
    }

    public function setHasFailedPaymentFlow($hasFailedPaymentFlow): self
    {
        $this->container['hasFailedPaymentFlow'] = $hasFailedPaymentFlow;
        return $this;
    }

    public function getIsConfirmed()
    {
        return $this->container['isConfirmed'];
    }

    public function setIsConfirmed($isConfirmed): self
    {
        $this->container['isConfirmed'] = $isConfirmed;
        return $this;
    }

    public function getIsCaptured()
    {
        return $this->container['isCaptured'];
    }

    public function setIsCaptured($isCaptured): self
    {
        $this->container['isCaptured'] = $isCaptured;
        return $this;
    }

    public function getIsCanceled()
    {
        return $this->container['isCanceled'];
    }

    public function setIsCanceled($isCanceled): self
    {
        $this->container['isCanceled'] = $isCanceled;
        return $this;
    }

    public function getCanBeCaptured()
    {
        return $this->container['canBeCaptured'];
    }

    public function setCanBeCaptured($canBeCaptured): self
    {
        $this->container['canBeCaptured'] = $canBeCaptured;
        return $this;
    }

    public function getDeeplink()
    {
        return $this->container['deeplink'];
    }

    public function setDeeplink($deeplink): self
    {
        $this->container['deeplink'] = $deeplink;
        return $this;
    }

    public function getWebhookUrl()
    {
        return $this->container['webhookUrl'];
    }

    public function setWebhookUrl($webhookUrl): self
    {
        $this->container['webhookUrl'] = $webhookUrl;
        return $this;
    }

    public function getAutoCapture()
    {
        return $this->container['autoCapture'];
    }

    public function setAutoCapture($autoCapture): self
    {
        $this->container['autoCapture'] = $autoCapture;
        return $this;
    }

    public function getSplitWithAmount()
    {
        return $this->container['splitWithAmount'];
    }

    public function setSplitWithAmount($splitWithAmount): self
    {
        $this->container['splitWithAmount'] = $splitWithAmount;
        return $this;
    }

    public function getIsMarketplace()
    {
        return $this->container['isMarketplace'];
    }

    public function setIsMarketplace($isMarketplace): self
    {
        $this->container['isMarketplace'] = $isMarketplace;
        return $this;
    }

    public function getIsRefundable()
    {
        return $this->container['isRefundable'];
    }

    public function setIsRefundable($isRefundable): self
    {
        $this->container['isRefundable'] = $isRefundable;
        return $this;
    }

    public function getIsDisputed()
    {
        return $this->container['isDisputed'];
    }

    public function setIsDisputed($isDisputed): self
    {
        $this->container['isDisputed'] = $isDisputed;
        return $this;
    }

    public function getRefundableAmount()
    {
        return $this->container['refundableAmount'];
    }

    public function setRefundableAmount($refundableAmount): self
    {
        $this->container['refundableAmount'] = $refundableAmount;
        return $this;
    }


    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed $value Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    public function isPaidSuccessfully(): bool
    {
        return
            $this->getIsCompleted() === true &&
            $this->getIsConfirmed() === true &&
            $this->getIsCaptured() === true &&
            $this->getIsCanceled() === false &&
            $this->getIsRefunded() === false &&
            $this->getTransaction()?->getStatus() === 'confirmed';
    }

    public function isPaymentFailed(): bool
    {
        return $this->getIsCompleted() &&
            (
                !$this->getIsCaptured() ||
                !$this->getIsConfirmed() ||
                $this->getHasFailedPaymentFlow()
            );
    }

    public function toArray(): array
    {
        return json_decode($this->toHeaderValue(), true);
    }
}